[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = ["/host-container"
]

[storage.options.pull_options]

[storage.options.overlay]
mountopt = "nodev"
